language: node_js
sudo: false
node_js:
    - 14
cache:
    directories:
        - node_modules
    npm: true
install:
    - lerna bootstrap
jobs:
    include:
        - stage: release
          script:
              - npm run build
              - npm run lint
              - npm run ci:test
          after_success:
              - bash <(curl -s https://codecov.io/bash)
