language: node_js
sudo: false
node_js:
    - 14
cache:
    directories:
        - node_modules
    npm: true
install:
    - npm install
jobs:
    include:
        - stage: release
          script:
              - npm run build:prod
              - npm run lint
              - npm run test -- --coverage
          after_success:
              - bash <(curl -s https://codecov.io/bash)
